# Generated by Django 4.0 on 2024-09-13 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_users_paidleave_remove_users_unpaidleave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='AssignedManager',
            field=models.ForeignKey(limit_choices_to={'role': 'MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_assigned_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('MANAGER', 'MANAGER'), ('EMPLOYEE', 'EMPLOYEE')], max_length=100),
        ),
    ]
